### PR TITLE
xdg-user-dirs support

### PR DESCRIPTION
**Pull request by outergod**
This is a quick fix to support [xdg-user-dirs](http://freedesktop.org/wiki/Software/xdg-user-dirs) if the script is run by a user, applicable if run e.g. by user crontab or crontab configuration.

### CODE REVIEW

**Comment by fs111** [comment]
I don't understand which problem this solves. I am running this as a normal user via crontab. crontab executes the script as the user, that installed the crontab. 

Which system are you on?

**Comment by outergod** [comment]
Hi André,

André Kelpe writes:

> I don't understand which problem this solves. I am running this as a normal user via crontab. crontab executes the script as the user, that installed the crontab. 
> it solves the problem of file system pollution by adhering to
> freedesktop.org standards. Other standard-conforming tools such as the
> built-in GNOME screenshot tool, normally triggered by pressing [print],
> also adhere to xdg-user-dir directories and place the pictures created
> this way into that location.

Of course, this doesn't apply to root, which would be the case for
non-user cron jobs.

> Which system are you on?
> Not that it matters here, but I'm on Fedora 17.

## 

Alexander Kahl    █▉    www: http://paralambda.org/
FSFE Fellow     █▉█▉█▉    e-mail: e-user@fsfe.org
Lambda Hacker     ▉▉    xmpp: e-user@jabber.fsfe.org

**Comment by fs111** [comment]
I get it now. Thanks for the patch, makes perfect sense.

**Comment by outergod** [comment]
Excellent,  thank you :+1:

**Pull request merged**
